### ISSUE TITLE
Missing support for some TLDs?

### ISSUE THREAD

**Issue by sklinkert** [garaekz/goshort#17]
I guess some of the newer TLDs are not accepted. For example https://etf.capital throws a `Your URL is invalid. Please provide a valid URL.`

Other TLD (.com, .net, .de) etc. work perfectly. Also https://etf.money works, with is funny because it's also a quite new TLD.

I think the issue is that `IsURL` (https://github.com/garaekz/goshort/blob/master/url/service.go#L46) is expecting a TLD length between 2 and five characters, but "capital" is 7. Maybe there are even longer TLDs out there.

**Comment by garaekz** [comment]
Hey, thanks for looking at my project, I'm currently doing a full rework of this to launch v2 where I fixed that issue, and yes, it's that regexp issue.

**Comment by garaekz** [comment]
Fixed with new release 2.0.0, this branch is now deprecated.
