### ISSUE TITLE
Problema con las minúsculas

### ISSUE THREAD

**Issue by zerofelx** [garaekz/goshort#4]
Buen día.

Existe un problema con respecto al acortador
A la hora de acortar aparentemente transforma el link a minúsculas.

Link original: https://www.youtube.com/watch?v=i_cVJgIz_Cs

Link acortado: s.h0rt.me/1rqp

Link saliente del short: https://www.youtube.com/watch?v=i_cvjgiz_cs

Como verás pone tanto la V como la C minúsculas, esto es un problema a la hora de usar links :D

Suerte amigo! 
Aparte de eso hiciste un asombroso trabajo!

**Comment by garaekz** [comment]
Lo atiendo directamente, gracias por apoyar

**Comment by garaekz** [comment]
Funcional con MySQL en entorno de desarrollo pero no en produccion, se reabre

**Comment by garaekz** [comment]
Solucionado con v1.2.4
